#!/usr/bin/env bash
#
# Copyright 2015-2018, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/test_nested/TEST3 : Test if subtx aborts correctly
#

# standard unit test setup
. ../unittest/unittest.sh

# this test verifies the correctness of the tx management functions only
#configure_valgrind pmemcheck force-disable

require_test_type medium
require_fs_type pmem non-pmem
require_build_type debug
require_pmemcheck_version_ge 1 0
require_pmreorder

setup

export PMEMOBJ_LOG_LEVEL=4
export PMEMOBJ_LOG_FILE=./trace_pmemobj$UNITTEST_NUM.log
TEST_NUM=4
LAYOUT="nested_test"
BIN="./test_nested_tx$EXESUFFIX"
PMEMCHECK_CMD="$BIN b $LAYOUT $DIR/testfile"
PMREORDER_CMD="$BIN d 4 $LAYOUT"
CREATE_POOL_CMD="$BIN p $LAYOUT $DIR/testfile"

echo "Log file is :"
echo $PMEMOBJ_LOG_FILE
echo "Creating obj pool ..."
echo $CREATE_POOL_CMD
$CREATE_POOL_CMD

echo "Creating store log ..."
echo "Log file is :"
echo $PMEMOBJ_LOG_FILE
pmreorder_create_store_log $DIR/testfile "$PMEMCHECK_CMD"

echo "Running consistency check ..."
echo "Log file is :"
echo $PMEMOBJ_LOG_FILE
pmreorder_expect_success NoReorderNoCheck pmreorder4.conf "$PMREORDER_CMD"

check

pass
